<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<!-- Plugin Version -->
		<Version>1.1.2.4</Version>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="RaidMax.IW4MAdmin.SharedLibraryCore" Version="2026.1.6.1" />
	</ItemGroup>

</Project>